# Generated by Django 3.2.6 on 2021-12-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalscore', models.CharField(max_length=100)),
                ('vicket', models.CharField(max_length=100)),
                ('balls', models.CharField(max_length=100)),
                ('over', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='topheading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theading', models.CharField(max_length=500)),
            ],
        ),
    ]
