# Generated by Django 3.2.6 on 2021-12-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_data', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Overs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b1', models.CharField(max_length=10)),
                ('b2', models.CharField(max_length=10)),
                ('b3', models.CharField(max_length=10)),
                ('b4', models.CharField(max_length=10)),
                ('b5', models.CharField(max_length=10)),
                ('b6', models.CharField(max_length=10)),
            ],
        ),
    ]
