# Generated by Django 3.2.6 on 2021-12-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0004_heading_overs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Over_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over', models.CharField(max_length=10)),
            ],
        ),
    ]
