# Generated by Django 3.2.6 on 2021-12-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0006_maindata'),
    ]

    operations = [
        migrations.CreateModel(
            name='welcomepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=100)),
                ('h2', models.CharField(max_length=100)),
            ],
        ),
    ]
