# Generated by Django 3.2.6 on 2021-12-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0007_welcomepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overs',
            name='b1',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
