# Generated by Django 3.2.6 on 2021-12-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0008_alter_overs_b1'),
    ]

    operations = [
        migrations.CreateModel(
            name='show_over',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sover', models.CharField(max_length=100)),
            ],
        ),
    ]
