# Generated by Django 3.2.6 on 2022-01-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0010_target_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batsman_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batman1', models.CharField(max_length=20)),
                ('batman2', models.CharField(max_length=20)),
                ('baller', models.CharField(max_length=20)),
            ],
        ),
    ]
